In [1]:
import pandas as pd
import joblib

In [2]:
#Dados
df_test = pd.read_csv("df_test.csv")

In [3]:
## Modelo de regressão
MODEL_FEATURES= ["rpm", "wind_speed", "current", "temperature", "vibration", "time_days"]
X_test = df_test[MODEL_FEATURES]
print("\nDados da observação:")

# Carregar o modelo 
modelo_xgb_reg = joblib.load("model_xgb_reg.pkl")

# teste
i = [10, 50]  # indice da tabela
X_observacao = X_test.iloc[i]
display(X_observacao)

# Predição utilizando o modelo carregado do arquivo .pkl
pred_xgb_reg = modelo_xgb_reg.predict(X_observacao)

# Criar a tabela de resultados
resultados = df_test.iloc[i].copy()

resultados["Predição RUL - XGBoost (.pkl)"] = pred_xgb_reg.round(2)

print("\nResultado real e predição:")
display(resultados)

Dados da observação:

          rpm  wind_speed    current  temperature  vibration  time_days
10  59.972562   24.520905  12.901479    57.242364   1.192200   0.208333
50  60.439081   14.094029  12.000524    52.515590   1.211648   1.041667

Resultado real e predição:

,timestamp,rpm,wind_speed,current,temperature,vibration,condition_state,RUL_days,Radar,time_days,Predição RUL - XGBoost (.pkl)
10,2024-03-09 19:51:50.398665,59.972562,24.520905,12.901479,57.242364,1.192200,SAUDÁVEL,273.520833,Radar 10,0.208333,271.149994
50,2024-03-10 15:51:50.398665,60.439081,14.094029,12.000524,52.515590,1.211648,SAUDÁVEL,272.687500,Radar 10,1.041667,272.850006

In [4]:
## Modelo de classificação
# Carregar o modelo salvo
modelo_xgb_cls = joblib.load("model_xgb_cls.pkl")
label_encoder = joblib.load("label_encoder.pkl")


# Predição utilizando o modelo carregado do arquivo .pkl
predicao_codificada = modelo_xgb_cls.predict(X_observacao).astype(int)
pred_xgb_cls = label_encoder.inverse_transform(predicao_codificada)

# Criar a tabela de resultados
resultados = df_test.iloc[i].copy()

resultados["Predição RUL - XGBoost (.pkl)"] = pred_xgb_cls

print("\nResultado real e predição:")
display(resultados)

Resultado real e predição:

,timestamp,rpm,wind_speed,current,temperature,vibration,condition_state,RUL_days,Radar,time_days,Predição RUL - XGBoost (.pkl)
10,2024-03-09 19:51:50.398665,59.972562,24.520905,12.901479,57.242364,1.192200,SAUDÁVEL,273.520833,Radar 10,0.208333,SAUDÁVEL
50,2024-03-10 15:51:50.398665,60.439081,14.094029,12.000524,52.515590,1.211648,SAUDÁVEL,272.687500,Radar 10,1.041667,SAUDÁVEL